### ISSUE TITLE
Todo list for CRAN submission

### ISSUE THREAD

**Issue by dwachsmuth** [UPGo-McGill/matchr#3]
- [x] Update progress reporting using new progressr API
- [x] Add remaining necessary class methods
- [x] Update shiny app to be more robust with large match sets
- [x] Rethink integrated start-to-finish function
- [x] Decide on best function names
- [x] Figure out code test coverage
- [ ] Write vignettes
